### ISSUE TITLE
Select control: Issue with Async options

### ISSUE THREAD

**Issue by MatthewMarkgraaff** [sherweb/ng2-materialize#112]
Hey there.

I'm having difficulty with pre-selecting async options within the `mz-select` control.  When generating options in the following way: 

`<option *ngFor="let language of _languages" [selected]="1==1"  [value]="language.id">{{ language.title }}</option>`

Only the last option is ever pre-selected (even with the selected property always set to true). I see on the demo page: https://sherweb.github.io/ng2-materialize/select there is an asynchronous select control with pre-populated options, how were you able to achieve this?

**Comment by charpeni** [comment]
Hi @MatthewMarkgraaff,

At the first look, it seems that your options are all selected as `[selected]="1==1"` is equivalent to `[selected]="true"`. Without a multi select you can't have multiple selected values, so if the last option is only pre-selected, it's normal.

To see how we've achieved this, you can checkout our demo-app component : https://github.com/sherweb/ng2-materialize/blob/master/demo-app/src/app/select/select.component.html#L200-L208

If you have any questions after that, feel free to ping us.

**Comment by MatthewMarkgraaff** [comment]
Hi @charpeni 

Thank you for the response, that makes sense. I'll ping you guys if I run into any issues, appreciate the assistance!
