### ISSUE TITLE
ModalService: How can I pass data into a modal component

### ISSUE THREAD

**Issue by lkhagen** [sherweb/ng2-materialize#113]
How can I inject state into the modal component? Maybe I'm overlooking something obvious here, but I can't seem to find a way to do this using the modal service.

**Comment by jfcere** [comment]
Hi @lkhagen,

I am not really sure what you mean by "inject state" into the modal component but if you mean how to pass values to your modal component using `MzModalService` you can declare `@Input` bindings in your modal component and pass the desired values using the second parameter `options` of the `open` method.

#### MzModalService
```typescript
open(componentClass: Type<MzBaseModal>, options: any = {}): ComponentRef<MzBaseModal>
```

#### Modal example
```typescript
import { Component, Input } from '@angular/core';
import { MzBaseModal } from 'ng2-materialize';

@Component({ ... })
export class ModalExampleComponent extends MzBaseModal {
  @Input() myModalProperty: string;
}
```

#### Open modal method
```typescript
public openServiceModal() {
  this.modalService.open(ModalExampleComponent, { myModalProperty: 'value-x' });
}
```

Let me know if it answers your question correctly.

**Comment by lkhagen** [comment]
That is perfect and exactly what I was hoping for (...and needed)! 

I don't understand how I missed that, given its also in the docs and all.

Thanks you helping out! :)

**Comment by jfcere** [comment]
No problem, don't hesitate if there is anything else.

**Comment by VadimDelSuper** [comment]
Is there a way to get modal **@Outpu**t from **_ExampleComponent_**??

**Comment by radikaledward1** [comment]
I would like to know if it is possible to create a @output decorator in the modal, pass a function o EventEmitter this is to recibe a response like a callback in the parent, all this via MZModalService.open();

**Comment by jfcere** [comment]
Take a look at this answer I gave in a similar issue to see if it helps: https://github.com/sherweb/ng2-materialize/issues/154#issuecomment-313412026

It should basically be the same way to do it by adding an `@Output()` property inside your modal and subscribing on it via the returned `ComponentRef`.

**Comment by radikaledward1** [comment]
Ok let me know if I'm right...¿Should I create a @Output decorator in the child (modal) like this "@Output callback = new EventEmitter();" and call it with "callback.emit();" ? and then use the "ComponentRef" intance to bind that function that i what to call in the parent like this... "this.modalComponentRef = <ComponentRef<ModalExampleComponent>>this.modalService.open(ModalExampleComponent);
this.modalComponentRef?.instance.callback = myparentfunction();" Is this correct? or What is the correct way to subscribe?, on another hand, How could i to close the modal using the ComponentRef?

**Comment by PriyaJainDev** [comment]
Is there any way to pass the parameters to openDialog() from the template and then access those parameters inside openDialog() method? 
Something like this:

**Inside angular template:** 

`<button (click)="openDialog(feeStructure)">Open it</button>`



**Component.ts:**
```
openDialog(value : string) {
    console.log(value); //this gives 'undefined'
    const dialogRef = this.dialog.open(InfoBoxComponent, {
      width: '500px',
      data: {
        rules: this.amount_rules,
        infoType: value  
      }
    });

    dialogRef.afterClosed().subscribe(result => {
      console.log('The dialog was closed');
    });
  }
```
