### ISSUE TITLE
error no exported member 'Renderer2'

### ISSUE THREAD

**Issue by misisriddle** [sherweb/ng2-materialize#114]
Hi,

I am having an error when I start npm now because of ng2-materialize. Here's the error I get:
WARNING in ./~/ng2-materialize/dist/collection/collection.component.js
33:12-21 "export 'Renderer2' was not found in '@angular/core'

ERROR in ....../node_modules/ng2-materialize/dist/collection/collection.component.d.ts (4,30): Module .../node_modules/@angular/core/index"' has no exported member 'Renderer2'.

How do I fix this?

Thank you!

**Comment by jfcere** [comment]
Hi @misisriddle,

When we updated the package to Angular 4 we noticed that `Renderer` has been deprecated and is replaced by `Renderer2` (you can find the reference [here](https://angular.io/docs/ts/latest/api/core/index/Renderer-class.html)).

We started to use `Renderer2` for this reason but I guess we forgot that this is against our efforts to keep the package compatible for both Angular 2 and 4 at least for now to give time to people to update.

I know this is not an ideal solution and we are sorry about this but by now the quick fix would be to update your application to Angular 4.

Note that Angular 4 brings many benefits such as performance boost so for that reason we encourage you to update. You can find a nice overview of the changes and benefits for updating to Angular 4 [here](http://angularjs.blogspot.ca/2017/03/angular-400-now-available.html).

That being said, we are going to sit back and see if there is anything we can do to avoid this issue in the short term but in the long run we are definitely going to move forward with Angular 4 and we are not planning to keep support with Angular 2.

**Comment by charpeni** [comment]
@misisriddle In the meantime, you should be fine with `ng2-materialize@1.3.2`.

```
npm install --save ng2-materialize@1.3.2
```

**Comment by jfcere** [comment]
@misisriddle as one of my collegue mentioned, in the meantime, you should be fine with ng2-materialize@1.3.2

```bash
npm install --save ng2-materialize@1.3.2
```

But obviously to get the new features and bug fixes you will need to update your applicaton to Angular 4.

**Comment by misisriddle** [comment]
Thank you @jfcere :) We don't have time to upgrade now to Angular 4 but will do so in the near future. Thanks again!
