### ISSUE TITLE
mz-input label is not set active when used with [(ngModel)]

### ISSUE THREAD

**Issue by ganeshkantu** [sherweb/ng2-materialize#117]
Hey,

I have a <mz-input> component with a [label] set and using it with [(ngModel)]. The data bound to this element is fetched from the server. When data is present, the label is not set to active - so the render looks like this:
![image](https://cloud.githubusercontent.com/assets/1470876/26040922/34fb8ba8-38f7-11e7-9077-5f0e59e73df5.png)

Expecting this:

![image](https://cloud.githubusercontent.com/assets/1470876/26040978/9ccc59a6-38f7-11e7-96b7-0b05c74718e5.png)

My element is declared like this:
```
<mz-input-container>
   <input mz-input [label]="'Case Name'" [validate]="true" [dataError]="'Case Name is required'" name="caseName" id="caseName" type="text" [(ngModel)]="case.name" [value]="case.name">
</mz-input-container>
```

Using NG 4.1.0 and ng2-materialize 1.3.2

**Comment by scote** [comment]
Can you verify if that's changed the behavior when you remove the attribute `[value]="case.name`?

**Comment by ganeshkantu** [comment]
It does the same even without [value].

**Comment by ganeshkantu** [comment]
This is what the render looks like from Chrome Dev Tools. As you can see, `class="active"` is missing from the label.

```
<mz-input-container _ngcontent-c3="" _nghost-c4="">
    <div _ngcontent-c4="" class="input-field">
        <input _ngcontent-c3="" id="caseName" mz-input="" name="caseName" type="text" class="validate ng-untouched ng-pristine ng-valid" ng-reflect-id="caseName" ng-reflect-data-error="Case Name is required" ng-reflect-label="Case Name" ng-reflect-validate="true" ng-reflect-name="caseName" ng-reflect-model="357325124">
        <label for="caseName" data-error="Case Name is required">Case Name</label>
    </div>
</mz-input-container>
```

**Comment by jfcere** [comment]
Hi @ganeshkantu,

Thank you for reporting the issue, we have been able to reproduce the problem. It should be investigated and fixed soon.

As a workaround, you can add `*ngIf` on the `mz-input-container` to render the input only when the value has been returned from the server.

```html
<mz-input-container *ngIf="case.name">
   <input mz-input [label]="'Case Name'" [validate]="true" [dataError]="'Case Name is required'" name="caseName" id="caseName" type="text" [(ngModel)]="case.name">
</mz-input-container>
```

**Comment by ganeshkantu** [comment]
@jfcere thanks! I will the try the *ngIf workaround and report back. However, the input element needs to be present for user-input as well - so can't use the *ngIf as a solution for my implementation.

**Comment by erathostene** [comment]
I guess also somehow related: When resetting the input value to null programmatically (ngModel or form reset), the '.active' class on the label isn't removed.
