### ISSUE TITLE
mz-checkbox-container and mz-radio-button-container

### ISSUE THREAD

**Issue by DarkIsDude** [sherweb/ng2-materialize#121]
Hi,

`<mz-checkbox-container class="col m3" *ngFor="let option of options">
    <input mz-checkbox [label]="option.name" type="checkbox" id="{{ option.id }}">
</mz-checkbox-container>`

With that, you can't select checkbox.
I want to do a plunker, but I don't know how include ngx-materialize... Sorry.

**Comment by scote** [comment]
Thanks I was able to reproduce your bug. We will look at this one soon.

**Comment by sevoan** [comment]
As workaround you can use 
`<input mz-checkbox [label]="option.name" [attr.id]="'option.id" id="{{ option.id }}">`

**Comment by jfcere** [comment]
Please take note that problem is also present for `mz-radio-button`.

@sevoan workaround can also be applied while we provide the fix:

```html
<mz-radio-button-container *ngFor="let option of options;">
  <input mz-radio-button
      [label]="option.text"
      [attr.id]="option.id"
      id="{{ option.id }}"
      name="radio-button-example"
      checked="checked"
      type="radio">
</mz-radio-button-container>
```
