### ISSUE TITLE
Select doesn't work when inside a Collapsible

### ISSUE THREAD

**Issue by renadlerossi** [sherweb/ng2-materialize#122]
Hi there,
I'm with a problem similar to issue 105 (https://github.com/sherweb/ng2-materialize/issues/105)

When I put Input elements inside a Collapsible, the Input is not rendered at all.
Select elements are rendered, but the functionality is gone (the options don't pop up).

Running a few tests I found out that even normal HTML elements with (click) do not trigger events from inside the Collapsible. Is this an expected behaviour?

**Comment by DarkIsDude** [comment]
Hi, it's a duplicate with #116 . They work on this issue.

**Comment by charpeni** [comment]
I'll reopen this issue since it's related to elements inside the Collapsible that don't work and the linked issue was about preselected behaviour.

**Comment by jfcere** [comment]
Hi @renadlerossi,

I'm am not able to reproduce your issue, could you please confirm if you're still having problems regarding inputs inside `mz-collapsible` component?

Here is the result of my test and some code sample I used.

Let me know if I can be of any help,

![select-in-collapsible](https://user-images.githubusercontent.com/6987084/27402892-5807c082-5696-11e7-80a9-8bb9d083ed1b.gif)

#### html
```html
<mz-collapsible [mode]="'accordion'">

  <mz-collapsible-item>
    <mz-collapsible-item-header>
        <i mz-icon-mdi [icon]="'heart'"></i>Select in collapsible
    </mz-collapsible-item-header>

    <mz-collapsible-item-body>
      <mz-input-container>
        <input mz-input
          [label]="'Label as placeholder'"
          id="basic-input"
          type="text">
      </mz-input-container>

      <mz-select-container>
        <select mz-select
          id="select"
          [label]="selectLabel"
          [placeholder]="selectPlaceholder"
          [disabled]="selectDisabled"
          [(ngModel)]="selectValue">
          <option *ngFor="let selectOption of selectOptions" [selected]="selectOption === selectValue">{{ selectOption }}</option>
        </select>
      </mz-select-container>
    </mz-collapsible-item-body>
  </mz-collapsible-item>

</mz-collapsible>
```

#### typescript
```typescript
selectOptions: string[];
selectValue: string;

ngOnInit() {
  // simulate 1000ms latency from server
  setTimeout(() => {
    this.selectOptions = ['Option 1', 'Option 2', 'Option 3'];
    this.selectValue = this.selectOptions[1];
  }, 1000);
}
```

**Comment by jfcere** [comment]
I am closing the issue as I am unable to reproduce the problem and got no response.

Feel free to reopen if there is anything!
