### ISSUE TITLE
[Angular 4] Sidenav requires page refresh to start working

### ISSUE THREAD

**Issue by Ondrazar** [sherweb/ng2-materialize#123]
I am using SideNav in my Angular 4 code which looks pretty much like SIDE NAV DEMO you have on http://materializecss.com/side-nav.html but the menu shows on the header only after login like this:

`<li *ngIf="authService.isAuthenticated()"><a data-activates="slide-out" class="button-collapse"><i class="material-icons">menu</i></a></li>`

However that causes the menu not to open after login unless you refresh the page.

Any suggestions or is this problem on materialize side? I don't want to use href as a workaround.

**Comment by Ondrazar** [comment]
derp, wrong github.

**Comment by scote** [comment]
You may use our librairie if your project use Angular 4.
