### ISSUE TITLE
ReactiveForms - validation not working

### ISSUE THREAD

**Issue by adrian5632** [sherweb/ng2-materialize#129]
Hi,

When using reactive forms I add several validators to an input marked with mz-input, however validation doesn't seem to be reflected:
**template:**
```
<mz-input-container class="col m6 s12">
        <i mz-icon-mdi mz-input-prefix
           [icon]="'cloud'">
        </i>
        <input mz-input
               [label]="'Nr służbowy'"
               [dataError]="'Niepoprawna wartość'"
               [dataSuccess]="'Wartość poprawna'"
               id="employee-id-input"
               length="{{fieldLengths.employeeId}}"
               type="text"
               [validate]="true"
               formControlName="employeeId"
        >
      </mz-input-container>
```
**component init:**
```
this.form = this.fb.group({
      employeeId: ['', [Validators.required, Validators.minLength(3), Validators.maxLength(6)]]
    })
```

When I type only 2 characters, it still shows the dataSuccess message instead of dataError. Is that supposed to work this way? If so, how can I use validators so that the invalid value is reflected in the UI?

**Comment by jfcere** [comment]
Hi @adrian5632,

The goal of this library is to wrap the original [Materialize](http://materializecss.com) framework to facilitate the use within Angular 2+.

Materialize leverage HTML5 validation and does not support reactive form validation _"out of the box"_. The validation is meant to be used by specifying HTML attributes that follows the [HTML5 validation spec](https://www.w3.org/TR/html5/forms.html#the-constraint-validation-api).

According to your code snippet, there is no HTML5 validation attribute therefore your field is always valid.

That being said, we coded a _"in house"_ prototype module that allows us to use reactive form validation with ng2-materialize library but it is not public and has not been fully proofed. We are going to talk about the possibility to make that extra module public next week and we'll keep you in touch.

**Comment by jfcere** [comment]
@adrian5632,

We are going to add the reactiveform validation support to the library within the next two weeks.
I'll keep the issue open until we publish the new version.
