### ISSUE TITLE
Collapsible > mz-collapsible-item > active not working

### ISSUE THREAD

**Issue by grzim** [sherweb/ng2-materialize#130]
Hello,

Setting a property `active` to `true` does not make a `collapsable-item` open. This issue is visible also in provided example under: https://sherweb.github.io/ng2-materialize/collapsible (Preselected Section)

Thanks for all your effort!

**Comment by charpeni** [comment]
It should be fine with `materializecss@0.98.2`, it doesn't work yet on gh-pages because it's only deployed on publication, but our herokuapp is synced with `master` branch : https://ng2-materialize.herokuapp.com/

Be sure you have at least `materializecss@0.98.2` and try this code :
<details>
  <mz-collapsible class="col s12 m8 l6" [mode]="'expandable'">

    <mz-collapsible-item [active]="true">
      <mz-collapsible-item-header>First</mz-collapsible-item-header>
      <mz-collapsible-item-body>
        <p>
          Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.
        </p>
      </mz-collapsible-item-body>
    </mz-collapsible-item>

    <mz-collapsible-item>
      <mz-collapsible-item-header>Second</mz-collapsible-item-header>
      <mz-collapsible-item-body>
        <p>
          Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.
        </p>
      </mz-collapsible-item-body>
    </mz-collapsible-item>

    <mz-collapsible-item>
      <mz-collapsible-item-header>Third</mz-collapsible-item-header>
      <mz-collapsible-item-body>
        <p>
          Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.
        </p>
      </mz-collapsible-item-body>
    </mz-collapsible-item>

  </mz-collapsible>
</details>

**Comment by charpeni** [comment]
Sorry, I thought it was already released, but it was not.

It should be fixed in release `ng2-materialize@1.4.2`.

**Comment by grzim** [comment]
great thank you!
