### ISSUE TITLE
Select component validation problem

### ISSUE THREAD

**Issue by taigosantos** [sherweb/ng2-materialize#153]
When change value of select component the css class don't change to ng-touched

**Comment by scote** [comment]
The materialize select is a custom element. It would be great if you can specify which element from the select should be marked to touched?

**Comment by taigosantos** [comment]
Only select is marked as touched, and when I use the command `this.myForm.reset()` the element don't reset too.

**Comment by scote** [comment]
You can trigger the `reset` function on form element. It should reset all materialize element to orginal state.

**Comment by scote** [comment]
You can try the `mz-validation` directive in the version 1.5.0.
