### ISSUE TITLE
Error: BrowserModule has already been loaded.

### ISSUE THREAD

**Issue by Rodrigo54** [sherweb/ng2-materialize#166]
I updated to the new version 1.5.0
And I'm getting this error

`Error: BrowserModule has already been loaded. If you need access to common directives such as NgIf and NgFor a lazy loaded module, import CommonModule instead.`

[![Capturar.jpg](https://s19.postimg.org/hu4wr6xyr/Capturar.jpg)](https://postimg.org/image/5fi4qv6gf/)

I'm using the `BrowserAnimationsModule` in the `AppModule` to animate my routes, I also have a `SharedModule` where I export the `MaterializeModule`. It would look something like this angular/angular#15829

In the previous version everything worked
#### Versions 
```
@angular/cli: 1.2.2
node: 8.1.3
os: win32 x64
@angular/animations: 4.3.1
@angular/common: 4.3.1
@angular/compiler: 4.3.1
@angular/core: 4.3.1
@angular/forms: 4.3.1
@angular/http: 4.3.1
@angular/platform-browser: 4.3.1
@angular/platform-browser-dynamic: 4.3.1
@angular/platform-server: 4.3.1
@angular/router: 4.3.1
@angular/cli: 1.2.2
@angular/compiler-cli: 4.3.1
@angular/language-service: 4.3.1
```
Thank you for the excellent abstraction of the materialize css that you have been carrying out

**Comment by scote** [comment]
We have the same error on our internal application. So, I am investigating on it.

**Comment by scote** [comment]
You can update your `ng2-materialize` version to `1.5.1` in your application.
