### ISSUE TITLE
stopPropagation=true doesn't work on programmatic dropDown

### ISSUE THREAD

**Issue by ganeshkantu** [sherweb/ng2-materialize#168]
Version: 1.5.1
NG 4.1.0

mz-dropdown triggered programmatically. [stopPropagation]=true doesn't stop event propagation and closes the dropdown on inside click.

Expected behavior: dropdown should remain open

Was working fine in 1.3.2

**Comment by scote** [comment]
Can you add an example of your code?

**Comment by scote** [comment]
Like Materialize said on their Dropdown page for the `stopPropagation` option : `If true, stops the event propagating from the drop down origin click handler.` That means if you add a drop down inside a clickable link collection item the drop down click will not trigger the collection link item click.

If you want to read more about the `stopPropagation` feature, you can read this issue : 
https://github.com/Dogfalo/materialize/issues/1683

You have a good ideal and you could open an issue to request this feature on Materialize repository :
https://github.com/Dogfalo/materialize/issues/new
