### ISSUE TITLE
DatePicker

### ISSUE THREAD

**Issue by KyDenZ** [sherweb/ng2-materialize#170]
Hello,

I would like to know if you have in your projects, to set date / time picker directly in module ng2-materialize

Thank you

**Comment by jfcere** [comment]
Hi @KyDenZ, we will one day but for now as we are a company building ng2-materialize for our applications we usually wait for us to need the component before to implement it.

We always welcome contribution! You could implement it if you want by cloning the repository and add the component (including tests) with related demo page.

**Comment by Rodrigo54** [comment]
Recently I implemented a datepicker but as I'm not very good with tests I could not do a pull request you can find the component in that gist https://gist.github.com/Rodrigo54/95ff2ee48b99bd4719c9dc2898eafd02

**Comment by scote** [comment]
Thank, It`s not exactly how we wrap the component but we will look at your code when we gonna do the DatePicker.

**Comment by enavarro222** [comment]
I use https://github.com/DanielYKPan/date-time-picker it is not based on materializecss, but it works well with it

**Comment by KyDenZ** [comment]
Ok thank

**Comment by jfcere** [comment]
Feature has been implemented and will be released in [v1.6.0](https://github.com/sherweb/ng2-materialize/milestone/2) which should come early october.
