### ISSUE TITLE
Events become unbound when using dropdown with *ngIf 

### ISSUE THREAD

**Issue by Liad91** [sherweb/ng2-materialize#171]
I'm using `*ngIf` attribute for the dropdown menu and his trigger button. when the expression toggles between `true ` and `false ` the events that were bound to the nested elements inside the dropdown become unbound.

### example:
**example.component.html**
```
<button mz-button id="btn-dropdown" *ngIf="x === 1">Open</button>

<button mz-button (click)="x = x * -1">Toggle</button>

<mz-dropdown [id]="'dropdown'" [dropdownButtonId]="'btn-dropdown'" [constrainWidth]="false" *ngIf="x === 1">
  <mz-dropdown-item>
    <a (mouseenter)="logMessage('mouseenter')">Button1</a>
  </mz-dropdown-item>
  <mz-dropdown-item>
    <a (mouseleave)="logMessage('mouseleave')">Button1</a>
  </mz-dropdown-item>
  <mz-dropdown-item >
    <a (click)="logMessage('click')">Button3</a>
  </mz-dropdown-item>
</mz-dropdown>
```
**example.component.ts**
```
@Component({
  ...
})
export class ExampleComponent {
  public x = 1;

  public logMessage(msg: string) {
    console.log(msg);
  }
}
```

**Comment by Liad91** [comment]
I managed to fix the issue by creating a new trigger directive for the dropdown component, and there I applied most of the logic from the component and added some handlers for the events. So the only logic that remained in the component is the input id. Now I'm using `*ngIf ` for the button only, and it's working like a charm. Let me know if you're interested in a PR. :wink:

**Comment by bumpmann** [comment]
I having a hard time with the delayed inits, if you can give more info about your fix ?

**Comment by LiadIdan** [comment]
@bumpmann I'm not sure what's the relationship between this issue to delayed inits but anyhow I've uploaded the fix to [StackBlitz](https://stackblitz.com/edit/ngx-materialize-dropdown)
