### ISSUE TITLE
mz-sidenav fixed property doesn't update inline styles to make it appear fixed when variable

### ISSUE THREAD

**Issue by mike-cao** [sherweb/ng2-materialize#173]
I am trying to have a sidenav that is fixed sometimes depending on certain conditions. To do this, I passed a boolean variable to mz-sidenav's [fixed] property.  When a user interaction causes the variable to become true, I can see that the component does add a "fixed" class to the side-nav ul, however, it's inline style of "transform: translateX(-100%);" remains, causing the sidenav to still appear off-screen. If I remove the inline-style, switching back and forth from fixed to not fixed seems to work as expected. Can the sidenav component remove any inline transform styles when it switches to from not fixed to fixed on the fly?

**Comment by scote** [comment]
Can you add example of your code? I will be easier to understand your problem.

**Comment by mike-cao** [comment]
No problem. This is the side-nav code that I'm using. It's pretty much the standard mz-sidenav component. In it, fixedSideNav is a boolean that defaults to false but can be set to true depending on the current view. When it's set to true, I can see upon inspection that the ul.side-nav has the "fixed" class, but it is still off-screen due to its inline-style of "transform: translateX(-100%);". My current workaround is to add "transform: translateX(0) !important;" in my css to the sidenav .fixed class, which overrides the inline style and makes it work as expected. This may be an issue with Materialize itself and not ng2-materialize. If so, please feel free to close this. Thank you.

`
  <mz-sidenav #sidenav
    [id]="'sidenav'"
    [collapseButtonId]="'btn-sidenav'"
    [closeOnClick]="true"
    [fixed]="fixedSideNav">

    <mz-sidenav-header>
      <div class="userView" *ngIf="_us?.user">
        <a routerLink="/account"><img class="circle" src="/assets/images/empty.png"></a>
        <a routerLink="/account"><span class="white-text name">{{_us?.user.FirstName}} {{_us?.user.LastName}}</span></a>
        <a routerLink="/account"><span class="white-text email">{{_us?.user.Email}}</span></a>
      </div>

      <div *ngIf="!_us?.user">
        <nav class="blue">
          <div class="nav-wrapper">
              <a routerLink="/products" class="brand-logo center">
              </a>
          </div>
        </nav>
      </div>
    </mz-sidenav-header>
  </mz-sidenav>
`

**Comment by jfcere** [comment]
Hi @mike-cao,

After investigation, the problem comes from Materialize as it does not allow to open the sidenav without having a modal background. Using `fixed` property does not allow to toggle between the two states either. We could do it but it does not trigger any opening/closing animations so basicly it would do the same to just set the `fixed` property to `true` and use `*ngIf="fixedSideNav` on the `mz-sidenav` element.

```html
<mz-sidenav #sidenav *ngIf="fixedSideNav"
  [id]="'sidenav'"
  [collapseButtonId]="'btn-sidenav'"
  [closeOnClick]="true"
  [fixed]="true">

  <mz-sidenav-header>
    <div class="userView" *ngIf="_us?.user">
      <a routerLink="/account"><img class="circle" src="/assets/images/empty.png"></a>
      <a routerLink="/account"><span class="white-text name">{{_us?.user.FirstName}} {{_us?.user.LastName}}</span></a>
      <a routerLink="/account"><span class="white-text email">{{_us?.user.Email}}</span></a>
    </div>

    <div *ngIf="!_us?.user">
      <nav class="blue">
        <div class="nav-wrapper">
            <a routerLink="/products" class="brand-logo center">
            </a>
        </div>
      </nav>
    </div>
  </mz-sidenav-header>
</mz-sidenav>
```

**Comment by mike-cao** [comment]
Thank you for your time in taking a look at this, @jfcere! My current workaround appears to be achieving what I need for now. Perhaps a Materialize contributor can figure this out sometime in the near future.

**Comment by jfcere** [comment]
@mike-cao you're welcome, we are here to help the best we can :)
