### ISSUE TITLE
Problems to pre-select options in mz-select

### ISSUE THREAD

**Issue by adrianomaringolo** [sherweb/ng2-materialize#174]
```
<mz-select-container class="col s6">
      <select id="select-group" multiple mz-select label="Groups" formControlName="groups" placeholder="Select">
          <option *ngFor="let option of availableGroups" [value]="option" [selected]="option.uuid == selectedGroup.uuid">{{ option.name }} </option>
     </select>
</mz-select-container>
```

```
availableGroups = [ 
    { "uuid": "ff8080815d09a25c015d09a360640000", "name": "Group 1" }, 
    { "uuid": "ff8080815d09a25c015d09ed20790002", "name": "Group 2" } 
] 
```

`selectedGroup =  { "uuid": "ff8080815d09a25c015d09ed20790002", "name": "Group 2" } `

I'm trying to render a select inside a form using Angular FormBuilder. I can create a new group normally with POST, when I select something in the select, my formControl values are updated correctly.

The problem is that I've been trying to pre-select one (or more) options when I render the form using the attr "selected" without success. Is there any mistake in the code above or there is something missing in the implementation of the mz-select component?

**Comment by scote** [comment]
I suggest you to remove `[selected]="option.uuid == selectedGroup.uuid"` its not recommmend to use this attribute.

**Comment by adrianomaringolo** [comment]
So the "selected" attribute would be bound by the values of the model?

I have another example in my code, a little simpler, using ngModel instead of formControlName.

```
<mz-select-container>
        <select id="select-status" mz-select [(ngModel)]="selectedStatus" multiple>
          <option *ngFor="let option of groupStatus" [value]="option.value">{{ option.label }}</option>
        </select>
</mz-select-container>
```

```
groupStatus = [{"value":"ACTIVE","label":"Active"},{"value":"INACTIVE","label":"Inactive"}]
selectedStatus = [{"value":"ACTIVE","label":"Active"}]
```

The same problem happens, the option "Active" should be pre-selected when the select component is rendered.

**Comment by scote** [comment]
In this exemple, you should use `ngValue` instead of `value` because your selected value is an object.

Here what it should look like :
```
<mz-select-container>
        <select id="select-status" mz-select [(ngModel)]="selectedStatus" multiple>
          <option *ngFor="let option of groupStatus" [ngValue]="option">{{ option.label }}</option>
        </select>
</mz-select-container>
```

**Comment by adrianomaringolo** [comment]
Thank you very, I removed the selected attr and kept the options values as strings, and it worked in both cases!

Tks again!
