### ISSUE TITLE
Error when trying to bind Error Message Resource

### ISSUE THREAD

**Issue by detchison** [sherweb/ng2-materialize#176]
I get the following error when trying to bind an error message resource on an input element:

Uncaught Error: Template parse errors:
Can't bind to 'errorMessageResource' since it isn't a known property of 'input'. ("     <input mz-input mz-validation required [label]="'First Name'" [validate]="true" id="firstName" [ERROR ->]

`<input mz-input mz-validation required [label]="'First Name'" [validate]="true" id="firstName" [errorMessageResource]="errorMessages.firstName" formControlName="firstName" type="text" placeholder="First Name"/>`

```  
  errorMessages = {
    firstName: {
      required: `A first name is required.`,
      minlength: `First name must be at least 2 characters.`,
      maxlength: `First name may be no more than 50 characters.`
    }
  }
```

**Comment by detchison** [comment]
I was able to get this to work by Importing the MzInputDirective, MzValidationComponent components into the component.. There is no mention of this in the documentation or the examples

**Comment by jfcere** [comment]
Hi @detchison, you should only need to import `MaterializeModule` in your Angular module as it already include both `MzInputDirective` and `MzValidationComponent`.

```typescript
import { NgModule } from '@angular/core';
import { FormsModule, ReactiveFormsModule } from '@angular/forms';
import { MaterializeModule } from 'ng2-materialize';

@NgModule({
  imports: [
    FormsModule,
    ReactiveFormsModule,
    MaterializeModule,
  ],
...
})
export class FormExampleModule { }

```

**Comment by detchison** [comment]
I wasnt able to get it to work that way. I am starting to think with this and other issues, i.e. setting the selected value of an mz-select not working, that there is some versioning issues perhaps...

**Comment by jfcere** [comment]
Can you add an example in your [detchison/ngmaterializeTest](https://github.com/detchison/ngmaterializeTest) repository? I'll could take a look at it ...

**Comment by detchison** [comment]
I was able to rectify the issue, not sure what it was, but just went and made sure everything was imported that way it should have been... sorry for the time waster.
