### ISSUE TITLE
Possible Contribution

### ISSUE THREAD

**Issue by detchison** [sherweb/ng2-materialize#178]
I am considering contributing, as i wrote a wrapper for the Datepicker, however i noticed that you are using Renderer and invokeElementFunction which have been deprecated. Your guide said to maintain the same style, but with this information its not wise to do so. What would you suggest? I have resorted to declaring a Jquery variable as it is the only other way to call one of these function such as .pickadate() in my case. The recommendations I have been reading have said to use the nativeelement to call this however the function doesnt seem to be accessible that way

**Comment by scote** [comment]
We use Renderer v1 and `invokeElementMethod` to stay compatible with Angular 2 even if the package is base on Angular 4+. When we began this package, Renderer2 was not existing at this moment and we did not migrate our code to use it.

So I recommend you to follow our style with `invokeElementMethod` and we will eventually change Renderer for the new one.
