### ISSUE TITLE
Any plans to integrate the Pagination component?

### ISSUE THREAD

**Issue by TryHardDood** [sherweb/ng2-materialize#181]
http://materializecss.com/pagination.html
Hope this helps: https://github.com/pleerock/ngx-paginator

**Comment by jfcere** [comment]
Hi @TryHardDood,

Wrapping pagination is not yet on our plate but we welcome any pull request that match our (thin) contribution guideline if you ever find the time to do the implementation.

Alternatively you can use the native Materialize pagination while waiting for it to be available through our library.

Also, depending on your needs, if found a nice tutorial on how to implement infinite-scroll feature: https://medium.com/@rintoj/building-virtual-scroll-for-angular-2-7679ca95014e

**Comment by TryHardDood** [comment]
Thanks for the info. 👍

**Comment by scote** [comment]
Fixed in #177
