### ISSUE TITLE
button toolbar

### ISSUE THREAD

**Issue by draco961** [sherweb/ng2-materialize#185]
Hello,

I have tried to use the button FAB to Toolbar but i can't access to the openToolBar method from materialize-css.js, the method is not there. Old version ?

**Comment by draco961** [comment]
Thanks for your help :-)

In the Materialize-css website, in Button section, you have a FAB-toolbar component (http://materializecss.com/buttons.html), and you can use it with jquery :  

  $('.fixed-action-btn.toolbar').openToolbar();
  $('.fixed-action-btn.toolbar').closeToolbar();


The problem is i can't access to those method with your ng2-materiliaze package.

**Comment by scote** [comment]
We did not have wrapped all features from FAB button. I suggest you to use your workaround until we addt hose methods.

**Comment by draco961** [comment]
Ok. thanks for your help
