### ISSUE TITLE
Floating label placeholder does not correctly reset on FormGroup.reset()

### ISSUE THREAD

**Issue by wnipper** [sherweb/ng2-materialize#187]
This is a minor annoyance, but when calling the FormGroup.reset() function, the floating label for the input does not reset to its original position.  It's easy to see on the live website.

To reproduce:

1. Go to forms validation on the [demo website](https://sherweb.github.io/ng2-materialize/form-validation).
2. Fill out the form normally.
3. Click the `Clear` button to clear the form.
4. Scroll up.  The labels for any field previously filled out will still be floating above, rather than on, the input.

Clicking in and out of inputs works as expected.  If you click on a field, enter some data, then clear that data and blur the field, the label returns to the correct position.

**Comment by scote** [comment]
You can call `Materialize.updateTextFields();` if you can to reset all label in the page.

**Comment by wnipper** [comment]
Perfect workaround.  Thank you.  And thanks for the quick response!

It would still be nice to have the controls reset when the form is reset.  NgForm and FormGroup both [inherit from the same parent](https://github.com/angular/angular/blob/4.3.4/packages/forms/src/model.ts#L958), so if you can figure out a way to hook the method it should work for both.  Unfortunately, the reset function doesn't have any lifecycle hooks; if it turns out to be impossible until the Angular team gives the function a lifecycle, I think just documenting the workaround would be perfectly acceptable.

**Comment by jfcere** [comment]
Please update to [v1.5.2](https://github.com/sherweb/ng2-materialize/releases/tag/v1.5.2) to get the fix
