### ISSUE TITLE
mz-select with reset button

### ISSUE THREAD

**Issue by jangelo08** [sherweb/ng2-materialize#192]
Hi.
Why is it that every time when the button is clicked and the value of "pfSelect.title" is changed to the default value. The select button won't change but the value will change. I tried to console.log the value and it changed. 

**tool-input.component.html**
```html
<mz-select-container class="col s12 m12 l12">
  <select mz-select id="pf-select" [(ngModel)]="pfSelect.title" [label]="'Pack Functionality'">
    <option *ngFor="let pfOption of pfOptions" [value]="pfOption.value" [disabled]="pfOption.disabled">{{pfOption.text}}</option>
  </select>
</mz-select-container>

<button mz-button class="white black-text" (click)="clear()" style="margin-top: 5px !important;">CLEAR</button>
```

**tool-input.component.ts**
```typescript
pfOptions = [
  { value: "1", text: "-- Choose --", disabled: true },
  { value: "Protect Only", text: "Protect Only", disabled: false },
  { value: "Promote/Gifting", text: "Promote/Gifting", disabled: false }
];

pfSelect = {
  title: "1"
};

clear() {
  this.pfSelect.title = "1";
}
```

**Comment by jfcere** [comment]
Hi @jangelo08,

Thanks for reporting the issue, the problem is probably related to the fact that the materialize select does not get refreshed but the value is correctly set.

We are going to investigate and fix it, we'll keep you in touch.

**Comment by jfcere** [comment]
Please update to [v1.5.2](https://github.com/sherweb/ng2-materialize/releases/tag/v1.5.2) to get the fix
