### ISSUE TITLE
Unable to dynamically toggle mz-collapsible-item(s)' active state

### ISSUE THREAD

**Issue by ShinRai1090** [sherweb/ng2-materialize#203]
I have come across an issue with mz-collapsible-item, wherein I'm trying to dynamically change the active state of the collapsible items. 

But when I change the [active] property to true, it only adds an active class to the header but does not open up the tab (or close the previous one).

## Expected Behavior
The tabs should get toggled, i.e. the _**li**_ element's active class should also get toggled, when the [active] property of any of the item is set to true.

## Current Behavior
Only the header is given the class "active", the _**li**_ element's class remains the same as before.

## Possible Solution
toggle the _**li**_ element's active class along with the header's and also the collapsible body's "display:block".

```
<mz-collapsible [mode]="'accordion'" [popout]="false">
  <mz-collapsible-item [active]="PIActive">
    <mz-collapsible-item-header>
      PI
    </mz-collapsible-item-header>
    <mz-collapsible-item-body>
      <PI Component>
    </mz-collapsible-item-body>
  </mz-collapsible-item>

  <mz-collapsible-item [active]="EDActive">
    <mz-collapsible-item-header>ED</mz-collapsible-item-header>
    <mz-collapsible-item-body>
      <ED Component>
    </mz-collapsible-item-body>
  </mz-collapsible-item>
</mz-collapsible>

```
So I'm dynamically toggling the PIActive and EDActive based on button clicks from within the PI Component or ED Component, using event emitters. The header's class gets toggled but same is not done for the li.

## Environment
* Version used: 1.5.1
* Angular version used: angular/cli 1.2.6
* Browser Name and version: Chrome Version 60.0.3112.113

**Comment by jfcere** [comment]
Thanks for reporting the issue, we're going to take a look at it and come back to you as soon as we can.

**Comment by jfcere** [comment]
Open/close functionnality has been added in [v1.8.1](https://github.com/sherweb/ng2-materialize/releases/tag/v1.8.1)
