### ISSUE TITLE
how to switch input radio

### ISSUE THREAD

**Issue by bellib** [sherweb/ng2-materialize#204]
<div class="col m6 s6 l6">
            <mz-radio-button-container>
              <input mz-radio-button
                [label]="'male' "
                [withGap]="true"
                id="radio-button-id"
                name="gender"
                formControlName="gender" 
                type="radio">
            </mz-radio-button-container>
          </div>
          <div class="col m6 s6 l6">
            <mz-radio-button-container>
              <input mz-radio-button
                [label]="'female'  "
                [withGap]="true"
                id="radio-button-id"
                formControlName="gender"
                name="gender" 
                type="radio">
            </mz-radio-button-container>
          </div>
```

**Comment by Liad91** [comment]
You have to use different `id` for each input.

**Comment by jfcere** [comment]
Hi @bellib,

@Liad91 is right, you have to use different `id` on each `mz-radio-button`. To group the radio buttons you just have to use the same `name` property.

**Comment by jfcere** [comment]
Closing issue, feel free to reopen if there is anything.
