### ISSUE TITLE
mz-select "multiple" does not separate the selected values with comma on version 1.5.2

### ISSUE THREAD

**Issue by CarlosAyala** [sherweb/ng2-materialize#206]
## Expected Behavior
When the user select the input values, they are shown separated with comma

## Current Behavior

The selected values ​​are not separated by commas and when the user deselects all values, the placeholder is not displayed.

## Context
This issue does not occurs on 1.5.1 version. This occurs on 1.5.2.

## Your Environment
* Version used: 1.5.2
* Angular version used: 4.3.2+
* Browser Name and version: Chrome or Mozilla
* Operating System and version (desktop or mobile): Ubuntu

**Comment by scote** [comment]
Thank you to report this bug. We will fix it on next version.

**Comment by jfcere** [comment]
Issue has been fixed and will be released in [v1.6.0](https://github.com/sherweb/ng2-materialize/milestone/2) which should come early october.
