### ISSUE TITLE
How to avoid mz-sidenav going back while clicking on the content ?

### ISSUE THREAD

**Issue by sijithc40** [sherweb/ng2-materialize#207]
## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used:
* Angular version used:
* Browser Name and version:
* Operating System and version (desktop or mobile):
* Link to your project (if appropriate):

**Comment by scote** [comment]
At this moment in Materialize, there is no option to configuration the sidenav close when clicking outside.

**Comment by jfcere** [comment]
Materialize fixed the behavior for sideNav for `closeOnClick` in v0.99.0 ([f97bf0b](https://github.com/Dogfalo/materialize/compare/v0.98.2...v0.99.0)).

Unfortunatly, we are currently using v0.99.2 that does not include the fix above.

So basically right now, the sideNav will close if...
- `closeOnClick === true`
OR
- `window.width < 992px` (no matter what `closeOnClick` value is)

This will be fixed when we will update to use Materialize v0.99.0 which we should do in a near futur.

Sorry for the inconvenience.

**Comment by sijithc40** [comment]
Thanks for the update :)
Is it possible "Push mode" ?

**Comment by jfcere** [comment]
We updated Materialize version 0.100.2 which include the fix for `closeOnClick` mentioned earlier.
This will be available in our next release [1.6.0](https://github.com/sherweb/ng2-materialize/milestone/2) planned for early october.

**Comment by jfcere** [comment]
@sijithc40 "push mode" does not seems to be a feature offer by Materialize library, therefore it is not provided through our library. Although this can probably be something achieved anyway with some tweek but I don't have any example for that matter.
