### ISSUE TITLE
Can close sidenav when clicking of close button in the menu?

### ISSUE THREAD

**Issue by sijithc40** [sherweb/ng2-materialize#208]
When asking general "how to" questions:

- Please do not open an issue here!
- Instead, ask for help on [StackOverflow](https://stackoverflow.com/) with Materialize and Angular tags.

- Read the [CONTRIBUTING document](https://github.com/sherweb/ng2-materialize/blob/master/CONTRIBUTING.md) Any issues that are violating the contributing guidelines, will be closed!
- [Search for duplicate or closed issues](https://github.com/sherweb/ng2-materialize/issues?utf8=%E2%9C%93&q=is%3Aissue) and make sure that is not an issue related to Materialize or other library.
- Prepare a [reduced test case](https://css-tricks.com/reduced-test-cases/) for any bugs.

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used:
* Angular version used:
* Browser Name and version:
* Operating System and version (desktop or mobile):
* Link to your project (if appropriate):

**Comment by scote** [comment]
May you add more detail about this bug?

**Comment by sijithc40** [comment]
Can I close the side menu when clicking on a button other than toggle?

**Comment by scote** [comment]
I don't understand your question. May you add an example of what you want to do?

**Comment by jfcere** [comment]
@sijithc40 a new `opened` state has been added to `mz-sidenav` to allow more flexibility on opening/closing the sidenav.

This should be available in our next release.

**Comment by sijithc40** [comment]
@scote Thanks, Is it possible push animation instead of overlay ?

**Comment by jfcere** [comment]
@sijithc40 Push animation is not something available "out of the box" with Materialize, which is the framework we are wrapping for Angular.

There has been a similar issue opened on which a way to toggle the sidenav is explained but it does not come with an animation and is not manage by our wrapper. See [https://github.com/sherweb/ng2-materialize/issues/231#issuecomment-339815658](https://github.com/sherweb/ng2-materialize/issues/231#issuecomment-339815658) for the how-to.
