### ISSUE TITLE
Using <i mz-icon-mdi and error in unit tests

### ISSUE THREAD

**Issue by ramden** [sherweb/ng2-materialize#211]
## Current Behavior

After setting up a clean angular 4 project and installing / adding ng2-materialize to the project and running a unit test for a component containing an material icon the unit test fails with following error:

> Can't bind to 'align' since it isn't a known property of 'i'. (""dropdown-button" data-activates="dropdown1">
	              test<i mz-icon-mdi
	                     [ERROR ->][align]="'right'"
	                     [icon]="'chevron-down'"></i>
	            </a>
	"): ng:///DynamicTestModule/HeaderComponent.html@23:21
	Can't bind to 'icon' since it isn't a known property of 'i'. ("
	              test<i mz-icon-mdi
	                     [align]="'right'"
	                     [ERROR ->][icon]="'chevron-down'"></i>
	            </a>
	          </li>
	"): ng:///DynamicTestModule/HeaderComponent.html@24:21
	Can't bind to 'icon' since it isn't a known property of 'i'. ("
	          <li>
	            <a>
	              <i mz-icon-mdi [ERROR ->][icon]="'magnify'"></i>
	            </a>
	          </li>
	"): ng:///DynamicTestModule/HeaderComponent.html@31:29
	Error: Template parse errors:
	    at syntaxError D:/work/projects/foodplan-angular/node_modules/@angular/compiler/@angular/compiler.es5.js:1694:22)

## Steps to Reproduce (for bugs)
1. Set up a clean angular 4 project using angular/cli
2. In AppComponent add **<i mz-icon-mdi [align]="'right'" [icon]="'chevron-down'"></i>**
3. Run **ng test**

## Your Environment

* Version used: 1.5.2
* Angular version used: 4.2.4
* Browser Name and version: Default settings for unit tests (Karma)
* Operating System and version (desktop or mobile): Windows 10 Pro x64 Desktop
* Link to your project (if appropriate): None (yet)

**Comment by jfcere** [comment]
Hi @ramden,  did you include `MaterializeModule` in your test setup? 

For example, with Angular-CLI using `TestBed` you would need to add the module to the test module configuration like this...

```typescript
beforeEach(async(() => {
  TestBed.configureTestingModule({
    imports: [ MaterializeModule.forRoot() ], // add MaterializeModule to testing module configuration
    declarations: [ HeaderComponent ],
  });
}));
```

**Comment by ramden** [comment]
You are right 👍 Thank you
