### ISSUE TITLE
Is it possible to have the sidenav open by default ?

### ISSUE THREAD

**Issue by noam1610** [sherweb/ng2-materialize#215]
In the documentation there is no property that say if the sidenav is shown or not.
Is there a simple way to handle it from the .ts ?

Thank you

**Comment by jfcere** [comment]
Hi @noam1610,

You are right, there is no property exposed on the `sidenav` component that says if it is opened or closed. Materialize added `onOpen` and `onClose` callback in version [0.99.0](https://github.com/Dogfalo/materialize/releases/tag/v0.99.0) which we are going to add in a near futur to the sidenav component. That way you'll have a hook on those events.

We're going to take a look if we can add this feature for the [1.6.0](https://github.com/sherweb/ng2-materialize/milestone/2) release that is planned soon. 

We'll keep you in touch!

**Comment by jfcere** [comment]
@noam1610 `onOpen` and `onClose` callback has been added and I added a `opened` state that will allow to tell you if the sidenav is opened or not. You will also be able to toggle the sidenav by changing the boolean value of the state.

This should be available in next releases.

For the part "Is it possible to have the sidenav open by default", you would need to toggle it manually in `ngAfterViewInit` or if you want it fixed you can use the `fixed` property on `mz-sidenav`.
