### ISSUE TITLE
All components should use ViewEncapsulation.None by default

### ISSUE THREAD

**Issue by IAMtheIAM** [sherweb/ng2-materialize#222]
All components should use  `ViewEncapsulation.None`

## Expected Behavior

Output HTML should not show `_ngcontent-*` etc attributes since they will not be utilized.

## Current Behavior

Currently, all but two use default  `ViewEncapsulation.Emulated`, which adds unnecessary markup to the outputted html. Since this framework is a wrapper for Materalize css framework, there is no reason to use view encapsulation since it already uses global styles. This will the output HTML very clean and easy to reason about.

I will be happy to do a PR if you approve this. If disapprove, please explain logic as to why.

**Comment by jfcere** [comment]
Hi @IAMtheIAM,

This is a good concern, we never thought about setting `ViewEncapsulation.None` as we wanted our component to be scoped like suggested by Angular (default value) but you make a good point saying that Materialize CSS already uses a global styles.

Of course we wouldn't want any bad behavior by switching but at the first sight the risks seems minimal. Please let us talk about it and we'll come back to you!

Btw thanks for bringing that up and wanting to help us.

**Comment by jfcere** [comment]
Quick question to help us understand the request...

**How does the added HTML `_ngcontent-*` affects your application in a way that you would like to not scope the css?**

Again you are right about the fact that Materialize css has been implemented to be used as global but we are more interested about the "why" ... we are big philosophers 😄

**Comment by IAMtheIAM** [comment]
OK, I will try to explain well. The reason why I don't like the `_ngcontent-*` is because I spend a lot of time reading the HTML inside chrome/firefox dev tools, in order to apply css styles within the devtools side panel, which allows me to real-time test how my CSS is going to look before I put it into my actual code file. But when there is all these strange generated attributes, it gets very confusing as to what the actual class is that I'm attempting to style. See the screenshots below.

With encapsulation
First `mz-content` one is with generated scopes. Second 
![with_encapsulation](https://user-images.githubusercontent.com/13709948/31732605-efc7f054-b3ed-11e7-8139-8bc7ea6f6ea7.png)

Without encapsulation
![without_encapsulation_1](https://user-images.githubusercontent.com/13709948/31732612-f2bea050-b3ed-11e7-8f68-68b76601c1f8.png)

It is much easy to read the second HTML than the first. Therefore, it is less fatique on my mind and eyes to read the clean HTML than to ready the encapsulated html, which is why I prefer that.

**Comment by IAMtheIAM** [comment]
What did you guys end up thinking about this suggestion?

**Comment by jfcere** [comment]
@IAMtheIAM sorry for the delay we have a lot on our plate.

We discussed about it and we think that easing css edition in the browser is not a valuable reason to remove encapsulation on components. We've seen frameworks do worst than that!

Although we mostly use Materialize CSS which is made to be global, we sometimes fix things with css while the real fix is being release on Materialize.

We don't have much customization but it happens sometimes that we add css and it would be messy to have some components with no encapsulation and other with default encapsulation.

We also modify the css in the browser sometimes before to implement it in the library and we never found that having `ng-content` was a big issue to go foward.

**Comment by IAMtheIAM** [comment]
OK, I understand its your guys decision. Although the reasoning I don't understand, because currently, ng2-materialize already has [mixed implementation](https://github.com/sherweb/ng2-materialize/search?utf8=%E2%9C%93&q=ViewEncapsulation&type=) of ViewEncapsulation.

Sidenav-link.component uses `ViewEncapsulation.Emulated`
But validation.component uses `ViewEncapsulation.None`
And on all other components, it is not specified.

I think as you said, it should be consistent. On all other components, it should be specified with `ViewEncapsulation.Emulated` if that is your team decision.

This is useful because it allows others to use `string-replace-loaders` with webpack and change that during compilation. But with no encapsulation specified, not only can this not be done, but it is also confusing as to the strategy the project is using. Please consider to add the `encapsulation` strategy to each component then for clarity.

I will even do the PR to add `ViewEncapsulation.Emulated` to each component to save you guys the time, if it will be approved.

**Comment by jfcere** [comment]
If my undestanding is right, and as per [Angular documentation](https://angular.io/api/core/ViewEncapsulation#members), `ViewEncapsulation.Emulated` is used by default when not specified.

For `sidenav-link.component` as it used `ViewEncapsulation.Emulated` it worth not much specifying what is the default value and we could remove it safely.

For `validation.component`, I spoke with @scote and he said it needs `ViewEncapsulation.None` to be able to apply css on the `mz-select` element. I can't really comment on that matter without further investigation but I trust my colleague :)

**Comment by scote** [comment]
We add to override CSS attributes for select and text area to make the validation directive displays correctly for those components. I would not have use this encapsulation strategy if we did not have to do those tricks.

**Comment by IAMtheIAM** [comment]
Ok yes, you are right, emulated is default angular encapsulation strategy, so that one for `sidenav-link.component` can be removed like you said. I accept the teams decision, it will be ok. Thanks for considering.

**Comment by yim222** [comment]
Hi, I want to say that this default value on Angular also cause that such problems :
https://stackoverflow.com/questions/44210786/style-not-working-for-innerhtml-in-angular-2-typescript

That the style don't accessible to injected Elements, and you need to define it on component level.

 I don't big architect, but maybe it causes a little confusing and  workaround vs.  React that  this the way things work, so I will be happy to understand why it's important to define.

I understand that the concern to conflicts with component's style. Is this the reason ?
