### ISSUE TITLE
MZCard: Naming convention of properties can be improved

### ISSUE THREAD

**Issue by IAMtheIAM** [sherweb/ng2-materialize#223]
Hi, me again. Right now I created this markup in Materalize

```html
   <div class="card-container">
      <div class="card col-24">
         <div class="card-content">
          Great Content Here.
         </div>
      </div>
   </div>

```

To do the same in ng2-materialize, the naming of the classes is a little unintuitive. 
This is the card template:
```html
<div
  class="card {{ backgroundClass }}"
  [class.hoverable]="hoverable">

  <div class="card-content {{ textClass }}">

    <div #cardTitle class="card-title" *ngIf="hasCardTitle">
      <ng-content select="mz-card-title"></ng-content>
    </div>

    <p>
      <ng-content select="mz-card-content"></ng-content>
    </p>
  </div>

  <div #cardAction class="card-action" *ngIf="hasCardAction">
    <ng-content select="mz-card-action"></ng-content>
  </div>
</div>
```

According to that, it means I would have to do this markup:

```html
   <mz-card [backgroundClass]="'col-24'">
      <mz-card-content>
            Great Content Here.
       </mz-card-content>
   </mz-card>
```
## Expected Behavior

Naming should be more generic to and according to its implementation

## Current Behavior

In your example docs, I can see why you guys chose to name it the way you did, but there are many use cases where `backgroundClass` would not be the appropriate name, such as applying column sizing to the card itself. The `col-24` needs to be applied to the `card` because applying it to `card-content` does not have any affect

## Proposed Solution

`backgroundClass` should be renamed to `cardClass`
`textClass` should be renamed to `cardContentClass`

It's a relatively small thing but it makes the code easier for another developer to come in and understand without having to read these docs.

**As a secondary question:** are there any real benefits of using this directive? What was the use case that prompted for its creation? It seems to basically output the same html as Material and there's not a whole lot of dynamic behavior associated with `cards` where being wrapped in angular is beneficial, as far as I can tell.

**Comment by scote** [comment]
I aggee with your suggestion about the naming. 

For your second question, you can see it is more simple to use compare the Materialize way. You are right about the card component behavior. When we did wrapped this component we had in mind to simply the way it shoud be use.

**Comment by jfcere** [comment]
I've came up with a way to avoid `backgroundClass` and `textClass` (or whatever naming we would come with) and use `class` directly on the `mz-card` component instead.

This brings a breaking changes for those using the grid system (classes such as `col s12`) directly on `mz-card`. The same way as it shouldn't be done on same element as `card` class with pure Materialize.

Meaning this will need to be done like this ...
```html
<div class="col s12">
  <mz-card class="blue-grey darken-1 white-text">
    <mz-card-content>
      Great Content Here.
    </mz-card-content>
  </mz-card>
</div>
```

**Comment by IAMtheIAM** [comment]
You guys are really fast! Thanks for taking this input and implementing so quickly. :-D

**Comment by jfcere** [comment]
You're welcome, we love what we do :)
