### ISSUE TITLE
MZSelectContainer: ngFor not iterating inside optgroup

### ISSUE THREAD

**Issue by darthsitthiander** [sherweb/ng2-materialize#243]
Hi there! I just noticed a bug which I'm not certain that it comes from ng2-materialize (might be angularfire2, in that case just ignore this). I assume it's this repo since if I remove the optgroup, it works fine. If you use Angular Firestore to retrieve data like this:

```Typescript
this.itemsCollection = this.db.collection<MarkerType>('items');
this.items = this.itemsCollection.valueChanges();
```

and then try to iterate through the items in html like this

```html
      <mz-select-container>
        <select mz-select
        id="options-select"
        [label]="'Label'"
        [placeholder]="'Placeholder'"
        >
         <optgroup label="Group 1">
          <option data-icon="assets/icons/icon1.png" class="left circle"  *ngFor="let item of items | async">{{ item.name }}</option>
         </optgroup>
        </select>
      </mz-select-container>
```

There are no tags created. I'm sorry I didn't provide a repo, but I believe this will be relatively easy to replicate. Cheers!

**Comment by jfcere** [comment]
Hi @darthsitthiander,

Thanks for reporting the issue, you are right... I tested the asynchronous initialization of the `mz-select` with `optgroup` and it did not work. As you said It does work without the `optgroup` tho.

We're going to look at it and come up with a fix.

In the meanwhile you could always initialize the select manually using jQuery with `$("#options-select").material_select()` once your asynchronous options has been returned.

![mz-select-optgroup](https://user-images.githubusercontent.com/6987084/33053409-698a9244-ce41-11e7-89b6-791d0439e76f.gif)

**Comment by darthsitthiander** [comment]
Thanks @jfcere , I'll try it out later today. So basically I can always fall back to the initialization functions of materialize-css? :) I'll be damned for not trying that before.

**Comment by jfcere** [comment]
You can always fallback to materialize-css initialization functions ... we only initialize components automaticaly to simplify the usage.

**Comment by jfcere** [comment]
@darthsitthiander the issue has been fixed and will be available in the next release.

**Comment by darthsitthiander** [comment]
@jfcere great work, thank you!
