### ISSUE TITLE
Materialize v1 : Dropdown

### ISSUE THREAD

**Issue by scote** [sherweb/ng2-materialize#245]
- [ ] Upgrade tpyings
- [ ] Migrate component https://github.com/Dogfalo/materialize/blob/v1-dev/v1-upgrade-guide.md#dropdown

**Comment by jfcere** [comment]
There is something wrong with Materialize v1 project? It should not create issues ...

**Comment by scote** [comment]
I convert this note to an issue in project. This way we can track the progression of each component and know who will do it.
