### ISSUE TITLE
Text inside parallax

### ISSUE THREAD

**Issue by Antonyselt** [sherweb/ng2-materialize#251]
## Expected Behavior
Triying to place text inside a palarax element

## Current Behavior
No text visible only buttons

## Steps to Reproduce (for bugs)
1. Put code for parallax elements
2. add h(1,2,3,4,5,6)  tags below img tag
3. see the result

## Context
I was trying to put some text inside parallax

## Your Environment

* Version used: the most recent acording to npm
* Angular version used: 5
* Browser Name and version: chrome, most recent
* Operating System and version (desktop or mobile): windows 10

**Comment by scote** [comment]
Thank you to report this bug.

I see the text appear behind the image.

You should open an issue on https://github.com/Dogfalo/materialize/issues this is not a bug related to this component.

**Comment by jfcere** [comment]
Althought this is not supported "out of the box" you could always play around with css to make it works...

#### css
```css
.parallax-text {
  position: absolute;
  bottom: 16px; /*optional, positioning example */
  z-index: 1;
}
```

#### html
```html
<mz-parallax [height]="300">
  <h2 class="parallax-text">Parallax text rulez!</h2>
  <img class="parallax-image" src="assets/parallax-1.png">
</mz-parallax>
```

![parallax-text](https://user-images.githubusercontent.com/6987084/33236817-757282f2-d22d-11e7-8ba9-60b9632381f5.gif)

**Comment by Antonyselt** [comment]
Thanks man, you are the best
