### ISSUE TITLE
Bad import for textarea

### ISSUE THREAD

**Issue by Antonyselt** [sherweb/ng2-materialize#252]
## Expected Behavior
Importing textareat like this
`import { MzTextareaModule } from 'ng2-materialize'`

## Current Behavior
You need to import textarea like this
`import { MzTextAreaModule } from 'ng2-materialize'`

## Possible Solution
Change the documentation for text area from this
`import { MzTextareaModule } from 'ng2-materialize'`

to this
`import { MzTextAreaModule } from 'ng2-materialize'`

## Steps to Reproduce (for bugs)
1. Go to text area documentation

**Comment by scote** [comment]
I made a mistake in the module name. It should be MzTextareaModule.

**Comment by jfcere** [comment]
@Antonyselt update to [v1.7.2](https://github.com/sherweb/ng2-materialize/releases/tag/v1.7.2) to get the fix ... the correct module name will be `MzTextareaModule` as specified in the [documentation](https://sherweb.github.io/ng2-materialize/textarea).
