### ISSUE TITLE
Why is MaterializeModule deprecated? And when will it be removed?

### ISSUE THREAD

**Issue by IAMtheIAM** [sherweb/ng2-materialize#255]
The readme says
`As an alternative, you can import `MaterializeModule` to make all component availables. This module is **deprecated** and it will be removed in a near future.`

But I see all the codebase still uses it here in the repo. Why is it deprecated, and when will it be removed?

**Comment by scote** [comment]
I will edit the readme with a better explanation. What we was trying to explain its those who are using `MaterializeModule` can still use it as we will continue to maintain. This way people will be able to migrate their component with the new way (import component module). For the new component we recommend to use the new way.

**Comment by scote** [comment]
I updated the readme with those informaiton (Fixed #257);
