### ISSUE TITLE
Text Area Module documentation error

### ISSUE THREAD

**Issue by clementvp** [sherweb/ng2-materialize#256]
In the  [docs](https://sherweb.github.io/ng2-materialize/textarea)

`import { MzTextareaModule } from 'ng2-materialize'`

must be :
`import { MzTextAreaModule } from 'ng2-materialize';`

If Not there an Error during compilation.

**Comment by Liad91** [comment]
This issue is a duplicate of #252, fixed by #253, which will be in the next release.

**Comment by clementvp** [comment]
Ok i'm closing in, but please for rookie (like me) consider to change the doc to be coherent with the code.
For me it's just a documentation mistake, nothing bad ;)

**Comment by scote** [comment]
Thanks for the reply @Liad91

**Comment by jfcere** [comment]
@clementvp update to [v1.7.2](https://github.com/sherweb/ng2-materialize/releases/tag/v1.7.2) to get the fix ... the correct module name will be `MzTextareaModule` as specified in the [documentation](https://sherweb.github.io/ng2-materialize/textarea).
