### ISSUE TITLE
Cannot load module in Meteor

### ISSUE THREAD

**Issue by apatryda** [sherweb/ng2-materialize#260]
Hello,

I was trying to load your module in [Meteor](https://www.meteor.com/) and got `unexpected token export` error.

As I did my research into the problem I noticed you are using es6 module loading in your lib's tsconfig while targeting the es5 at the same time.

This is a problem as your module needs to be recompiled with Babel before minification and Meteor doesn't provide a way to do so with node modules (it expects them to be in plain es5).

What is your motivation in using es6 modules while targeting the es5 and is it possible to change it to tsconfigs default which is commonjs?

I'm using Meteor 1.6 with Angular 5 and Urigo's [angular compilers](https://github.com/Urigo/angular-meteor/tree/master/atmosphere-packages/angular-compilers).

**Comment by jfcere** [comment]
@apatryda, this is a good and fair question ... i'll investigate and come back to you shortly.

**Comment by jfcere** [comment]
I've changed module code generation to commonjs and tested the transpiled library in another application and it seems to work fine.

Please update to v1.8.0-beta.0 and tell me if it solves your issue.

**Comment by apatryda** [comment]
It works now :)

Meteor expect external libraries to be ES5 as in flavor of the language. ES5 didn't have an integrated module loader. You had to use something external like CommonJS or AMD. TypeScript and Angular Compiler default use CommonJS by default.
