### ISSUE TITLE
Cannot find namespace 'Materialize'

### ISSUE THREAD

**Issue by IAMtheIAM** [sherweb/ng2-materialize#265]
I get `Cannot find namespace 'Materialize'` when trying to build the app
  
Looks like the new `@types/materialize-css@^1.0.1` module has a different structure:

```
// Type definitions for materialize-css 1.0
// Project: http://materializecss.com/
// Definitions by:  胡玮文 <https://github.com/huww98>
// Definitions: https://github.com/DefinitelyTyped/DefinitelyTyped
// TypeScript Version: 2.4

/// <reference types="jquery" />

export = M;

declare global {
    namespace M {
        class Autocomplete extends Component<AutocompleteOptions> {
     ...
    }
}

```

They use `M` instead of `Materialize` where as this package still uses `@types/materialize-css@^0.100.0`. How to fix this conflict? As far as I know I can only specify one `typesRoot` and that will reference the new version.

**Comment by jfcere** [comment]
This is the typings for version 1.0 of Materialize while we are using version 0.100.2.
Be sure to have `@types\materialize-css` witing 0.100.x range.

**Comment by IAMtheIAM** [comment]
OK I see. I'll have to remember that. Any plans to update to the new 1.x?

**Comment by jfcere** [comment]
Materialize v1.0 is still in alpha ... we do have plans to move forward to this version but we were pretty much waiting for a beta version before to proceed with the migration to avoid to many refactor on our hands.

**Comment by IAMtheIAM** [comment]
OK that is understandable

**Comment by jfcere** [comment]
Closing but don't worry we still have an eye on Materialize v1.0
