### ISSUE TITLE
How to close sidenav after clicking a router link?

### ISSUE THREAD

**Issue by hoangnguyen208** [sherweb/ng2-materialize#269]
`closeOnClick` property can close on `href` link, but this behavior does not work on `routerLink`. Any suggestion please?

**Comment by LiadIdan** [comment]
@hoangnguyen208 check this [demo](https://stackblitz.com/edit/angular-n9umri?file=app%2Fapp.component.html), it seems to work fine.

**Comment by hoangnguyen208** [comment]
Oh sorry, I forgot the square bracket. Thank you
