### ISSUE TITLE
Add support for non-english characters in mz-tab-item label property

### ISSUE THREAD

**Issue by Mesya82** [sherweb/ng2-materialize#270]
## Expected Behavior
When using non-english characters in label property all functionality should work same as with english characters

## Current Behavior
Exception "Syntax error, unrecognized expression: #%D0%B1%D0%B8%D0%B7%D0%BD%D0%B5%D1%81%D1%81-%D0%BC%D0%BE%D0%B4%D0%B5%D0%BB%D1%8C" occurs

## Possible Solution
Maybe it is something to do with encoding. My Angular app uses UTF-8.

## Steps to Reproduce (for bugs)
1. Create basic tab structure
2. Use non-english characters in mz-tab-item label property("Таб 1", "Таб 2", "Таб 3")
3. Load app, notice exception thrown already
4. Try to change tabs

## Your Environment
* Version used: 1.8.0-beta.0
* Angular version used: 5.2.0
* Browser Name and version: Chrome, latest version
* Operating System and version (desktop or mobile): Windows 10 16299

**Comment by scote** [comment]
May you do an example on Stackblitz?

**Comment by LiadIdan** [comment]
@scote I found the [cause](https://github.com/sherweb/ng2-materialize/blob/master/src/app/tab/tab-item/tab-item.component.ts#L27) of the problem.
Mayby we should replace the link getter with an id input?

**Comment by Mesya82** [comment]
> May you do an example on Stackblitz?
https://stackblitz.com/edit/ngx-materialize-9tng1a
