### ISSUE TITLE
Can't access an object that is inside mz-tab with @ChildView 

### ISSUE THREAD

**Issue by masfaraud** [sherweb/ng2-materialize#271]
## Expected Behavior

It should be possible to get an element which is inside a mz-tab from angular with @ChildView 

## Current Behavior

Angular fails to access an element inside a mz-tab. It works for mz-card for example

## Steps to Reproduce (for bugs)

Here is an example where I tried to reproduce the problem. I think there is a problem with the tabs imported in stackblitz because there is an additional problem with the tabs.
I am trying to access to the <div> with id "element" from angular with ChildView 
https://stackblitz.com/edit/ngx-materialize-hv1ewb

## Your Environment

* Version used: 1.8.0-beta.0
* Angular version used: 5.1.2
* Browser Name and version: firefox 57.0.3
* Operating System and version (desktop or mobile): Linux Mint

**Comment by LiadIdan** [comment]
@masfaraud I've checked your StackBlitz, and it seems to work fine.
Try this line inside the `ngAfterViewInit` method `this.element.nativeElement.innerHTML = 'Hello world';`

**Comment by masfaraud** [comment]
@LiadIdan  I added your suggestion, I still have the tabs problem on stackblitz, which doesn't occurs on my side, so I guess this is a problem of stackblitz
![console](https://user-images.githubusercontent.com/14061753/35194232-65ea2f60-feb0-11e7-8d27-7a444b4cfc6f.png)

**Comment by masfaraud** [comment]
I have checked on a minimal example, you're right it works find. I didn't manage to make it work on my larger project maybe because of collision between materializecss and ng2-materializecss...

[tabs-childview.zip](https://github.com/sherweb/ng2-materialize/files/1649775/tabs-childview.zip)
