### ISSUE TITLE
Add weekdaysLetter to options on datePicker

### ISSUE THREAD

**Issue by radoslawdabrowski** [sherweb/ng2-materialize#272]
## Expected Behavior
Hi, I have problem with translation the datepicker, because I need to use key `weekdaysLetter` in `Pickadate.DateOptions` which is provided by orginal materializecss library, but here it seems to be not implemented.

## Current Behavior

Its seems to work fine when app is on dev mode, npm compile it just fine, the problem shows when I try to run a `ng build --prod`, then it throws exception

> Object literal may only specify known properties, and 'weekdaysLetter' does not exist in type 'DateOptions'.

## Possible Solution
Add `weekdaysLetter?: string[];` to `Pickadate.DateOptions` 
(I did that locally and seems to work fine)

## Steps to Reproduce (for bugs)
1. https://stackblitz.com/edit/ngx-materialize-etmuun

## Context
Tying to compile the production version of app.

## Your Environment
* Version used: 1.8.0-beta.0
* Angular version used: 5.2.0
* Browser Name and version: Opera/Chrome - Latest version
* Operating System and version (desktop or mobile): Desktop/Windows 10.0.16299.192

**Comment by LiadIdan** [comment]
The issue has been [resolved](https://stackblitz.com/edit/ngx-materialize-nxyef8?file=app/app.component.ts).

**Comment by jfcere** [comment]
I am going to update the typings once it as been published.

**Comment by LiadIdan** [comment]
@jfcere it's already been published

**Comment by jfcere** [comment]
@LiadIdan update is on the way!

**Comment by radoslawdabrowski** [comment]
Great! Thank you for fast response :)
