### ISSUE TITLE
Show weekdays short with other language

### ISSUE THREAD

**Issue by LucasViniciusPereira** [sherweb/ng2-materialize#274]
Hello,

I'm using datepicker with language pt-br, but don't show in header weekdays in datepicker in portugues,
is showing in english.

![code](https://user-images.githubusercontent.com/6699391/35435530-32945120-0272-11e8-87eb-956049747a4c.JPG)

![datepicker](https://user-images.githubusercontent.com/6699391/35435434-de9a68ac-0271-11e8-873d-8e286ec75df7.png)

**Comment by radoslawdabrowski** [comment]
Hi, I think its connected to my issue (I tried to translate to polish)
https://github.com/sherweb/ng2-materialize/issues/272

The option you need is 
weekdaysLetter : ['N', 'P', 'W', 'Ś', 'C', 'Pt', 'S']
but it seems to be bugged
it seems to work but

**Comment by jfcere** [comment]
I am going to update the typings once it has been published.

**Comment by LucasViniciusPereira** [comment]
Thanks @radoslawdabrowski issue resolved.

**Comment by jfcere** [comment]
Closing issue, you can follow #272 for the typings issue
