### ISSUE TITLE
Control navbar content disappearance depending on screen size

### ISSUE THREAD

**Issue by masfaraud** [sherweb/ng2-materialize#281]
I'm asking for a feature request for setting a parameter to control on which size of screen the navbar content should disappear.

## Expected Behavior

In materializecss, this behavior can be controled with classes hide-on-med-and-down and so on.

## Current Behavior

In Ng2-materialize, this behavior can't be changed and the content disappear for medium and small screens.

It should be possible to control the size of screen making disappear the navbar content (medium or small).

## Possible Solution

The hide on medium and small is currently hardcoded, exemple of **navbar/navbar-item-container/navbar-item-container.component.html:**
````
<ul id="nav-mobile" class="{{ align }} hide-on-med-and-down">
  <ng-content></ng-content>
</ul>
````

**Comment by jfcere** [comment]
Hi @masfaraud, 

You are right, this should not be hardcoded, i will remove it.

**Comment by masfaraud** [comment]
Great! Thanks for your time and for your reactivity!
