### ISSUE TITLE
Color of inputs

### ISSUE THREAD

**Issue by Raiper34** [sherweb/ng2-materialize#290]
Hi, please I need help, how to change color of input? In materializecss i can do this:
`.input-field label  
{  
  color: $primary-color;  
}  
.input-field input[type=text]:focus + label
{
  color: $primary-color;
}
.input-field input[type=text]:focus
{
  border-bottom: 1px solid $primary-color;
  box-shadow: 0 1px 0 0 $primary-color;
}`

But in ng2-materialzie it does not work :(

**Comment by scote** [comment]
You have to use `::ng-deep` to override the input component style.

You can have more details at this page : https://angular.io/guide/component-styles#deprecated-deep--and-ng-deep

**Comment by Raiper34** [comment]
It works on unfocused inputs, but when I focus input it does not work and still same default color

`
$primary-color: #ff5722;

::ng-deep .tabs .indicator
{
  background-color: $primary-color;
}
::ng-deep .input-field label
{
  color: $primary-color;
}
::ng-deep .input-field input[type=text]:focus + ::ng-deep label
{
  color: $primary-color;
}
::ng-deep .input-field input[type=text]:focus
{
  border-bottom: 1px solid $primary-color;
  box-shadow: 0 1px 0 0 $primary-color;
}
::ng-deep .input-field input[type=password]:focus + ::ng-deep  label
{
  color: #ff5722;
}
::ng-deep .input-field input[type=password]:focus
{
  border-bottom: 1px solid $primary-color;
  box-shadow: 0 1px 0 0 $primary-color;
}

`

**Comment by scote** [comment]
Can you make a StackBlitz example ?
https://stackblitz.com/edit/ngx-materialize

I will be easier to help you.

**Comment by Raiper34** [comment]
@scote here is my StackBlitz https://stackblitz.com/edit/ngx-materialize-epmy8o?file=app%2Fapp.component.scss

**Comment by scote** [comment]
Add a class on your `input-container` tag and add the class name to your scss before each selector. This should fix your problem.

**Comment by Raiper34** [comment]
Tank yoy very much :)
