### ISSUE TITLE
Textarea not working with Angular 5

### ISSUE THREAD

**Issue by darthsitthiander** [sherweb/ng2-materialize#292]
I'm sorry to open that many issues lately, you guys must hate me :p 

When adding a Textarea

#Expected behavior
A textarea appears and can be used

#Current behavior
Getting following error message: Unexpected closing tag "mz-textarea-container". It may happen when the tag has already been closed by another tag. 

Stackblitz URL: https://stackblitz.com/edit/ngx-materialize-k7pjuv

**Comment by jfcere** [comment]
You didnt close your `<i>` tag ;)

**Comment by darthsitthiander** [comment]
How stupid of me not to notice! Thank you! It should be updated in the docs as well ;)

**Comment by jfcere** [comment]
Err you are right, sorry i'll correct the example in the demo page.
