### ISSUE TITLE
"width" property on sidenav has no affect

### ISSUE THREAD

**Issue by theiviaxx** [sherweb/ng2-materialize#308]
1. Add <mz-sidenav [width]="400" [fixed]="true">...</mz-sidenav> to a component
2. ---> Note that the sidenav element is still at 300px

**Comment by jfcere** [comment]
I tried it on StackBlitz and it seems ok: https://stackblitz.com/edit/ngx-materialize-sidenav

**Comment by theiviaxx** [comment]
Hmmm, i must be doing something wrong elsewhere.  Thanks for following up!

**Comment by theiviaxx** [comment]
Ok i was missing the [id] property, so +1 to reading the docs :)

**Comment by jfcere** [comment]
Cool! I'm glad you found out :)
