### ISSUE TITLE
Update to angular@6.0 and rxjs@6.1

### ISSUE THREAD

**Issue by Albejr** [sherweb/ng2-materialize#316]
## Expected Behavior
Necessary to compatibility of import paths to new structure.

## Current Behavior
![image](https://user-images.githubusercontent.com/24717256/39648335-3e98cd6e-4fb8-11e8-83d8-068ed323d657.png)

## Your Environment
```
Angular CLI: 6.0.0
Node: 8.11.1
OS: win32 x64
Angular: 6.0.0
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, material, platform-browser
... platform-browser-dynamic, platform-server, router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.6.0
@angular-devkit/build-angular     0.6.0
@angular-devkit/build-optimizer   0.6.0
@angular-devkit/core              0.6.0
@angular-devkit/schematics        0.6.0
@angular/cdk                      5.2.5
@angular/http                     5.2.10
@ngtools/webpack                  6.0.0
@schematics/angular               0.6.0
@schematics/update                0.6.0
rxjs                              6.1.0
typescript                        2.7.2
webpack                           4.6.0
```

**Comment by scote** [comment]
We will look to upgrade the lib to version 6 soon.

**Comment by maroy1986** [comment]
Meanwhile, you can and must install `rxjs-compat` package, which is also a new dependency for Angular 6 at the moment to maintain compatibility with rxJS 6.x branch.

**Comment by LucasViniciusPereira** [comment]
I need too

**Comment by jfcere** [comment]
Repository has been updated to Angular 6 and renamed to `ngx-materialize`, you will need to uninstall `ng2-materialize` and install `ngx-materialize`.

Please refer to the [v6.0.0 Release Note](https://github.com/sherweb/ngx-materialize/releases/tag/v6.0.0) or [README.md](https://github.com/sherweb/ngx-materialize/blob/master/README.md) for more information.
