### ISSUE TITLE
Date picker - How Modify default Language

### ISSUE THREAD

**Issue by cianciagiovanni** [sherweb/ng2-materialize#373]
Hi, 
how and where to change the default date picker language? I found from the documentation the code that interests me (https://github.com/amsul/pickadate.js/blob/3.6.2/lib/translations/it_IT.js) but I don't know where to apply it for my angular web application that use the mz-datepicker component
Thank you

**Comment by leandrorazevedo** [comment]
Hi, 
first, create a variable like : 
```

const datepickerOptions: Pickadate.DateOptions = {
    monthsFull: [ 'gennaio', 'febbraio', 'marzo', 'aprile', 'maggio', 'giugno', 'luglio', 'agosto', 'settembre', 'ottobre', 'novembre', 'dicembre' ],
    monthsShort: [ 'gen', 'feb', 'mar', 'apr', 'mag', 'giu', 'lug', 'ago', 'set', 'ott', 'nov', 'dic' ],
    weekdaysFull: [ 'domenica', 'lunedì', 'martedì', 'mercoledì', 'giovedì', 'venerdì', 'sabato' ],
    weekdaysShort: [ 'dom', 'lun', 'mar', 'mer', 'gio', 'ven', 'sab' ],
    today: 'Oggi',
    clear: 'Cancella',
    close: 'Chiudi',
    firstDay: 1,
    format: 'dddd d mmmm yyyy',
    formatSubmit: 'yyyy/mm/dd',
    labelMonthNext: 'Mese successivo',
    labelMonthPrev: 'Mese precedente',
    labelMonthSelect: 'Seleziona un mese',
    labelYearSelect: 'Seleziona un anno'
};
```

after, in your template : 

```
<mz-datepicker-container>
        <i mz-icon-mdi mz-input-prefix [icon]="'calendar'"> </i>
        <input
          mz-datepicker
          required
          type="text"
          [options]="datepickerOptions"
        />
</mz-datepicker-container>

```

Regards,

**Comment by cianciagiovanni** [comment]
thank you so much, it works

> 
> 
> Hi,
> first, create a variable like :
> 
> ```
> 
> const datepickerOptions: Pickadate.DateOptions = {
>     monthsFull: [ 'gennaio', 'febbraio', 'marzo', 'aprile', 'maggio', 'giugno', 'luglio', 'agosto', 'settembre', 'ottobre', 'novembre', 'dicembre' ],
>     monthsShort: [ 'gen', 'feb', 'mar', 'apr', 'mag', 'giu', 'lug', 'ago', 'set', 'ott', 'nov', 'dic' ],
>     weekdaysFull: [ 'domenica', 'lunedì', 'martedì', 'mercoledì', 'giovedì', 'venerdì', 'sabato' ],
>     weekdaysShort: [ 'dom', 'lun', 'mar', 'mer', 'gio', 'ven', 'sab' ],
>     today: 'Oggi',
>     clear: 'Cancella',
>     close: 'Chiudi',
>     firstDay: 1,
>     format: 'dddd d mmmm yyyy',
>     formatSubmit: 'yyyy/mm/dd',
>     labelMonthNext: 'Mese successivo',
>     labelMonthPrev: 'Mese precedente',
>     labelMonthSelect: 'Seleziona un mese',
>     labelYearSelect: 'Seleziona un anno'
> };
> ```
> 
> after, in your template :
> 
> ```
> <mz-datepicker-container>
>         <i mz-icon-mdi mz-input-prefix [icon]="'calendar'"> </i>
>         <input
>           mz-datepicker
>           required
>           type="text"
>           [options]="datepickerOptions"
>         />
> </mz-datepicker-container>
> ```
> 
> Regards,

**Comment by cianciagiovanni** [comment]
thank you so much, it works
