### ISSUE TITLE
Bug in Sidenav Collapsible Header in Angular 4

### ISSUE THREAD

**Issue by Rodrigo54** [sherweb/ng2-materialize#86]
in [line 4 of template](https://github.com/sherweb/ng2-materialize/blob/master/src/app/sidenav/sidenav-collapsible/sidenav-collapsible.component.html#L4) of MzSidenavCollapsibleHeaderComponent are used `[innerHTML]` property and it generate warning in angular 4

[![Capturar.jpg](https://s19.postimg.org/lynbi1pf7/Capturar.jpg)](https://postimg.org/image/uto5ske7j/)

It is also no longer possible to use the click event on this component

```html
<mz-sidenav-collapsible-header (click)="onClick($event)">
   <i mz-icon-mdi [icon]="'menu-right'" class="caret"></i>Collapsible
</mz-sidenav-collapsible-header>
```
In the previous version these problems did not exist
Does anyone have an opinion on this? Thank you very much in advance

**Comment by charpeni** [comment]
Thank you for the reporting.

Unfortunately we are not using Angular 4 yet, we will check it out soon when we're going to update.

In the meantime, PRs are welcome.

**Comment by scote** [comment]
You will be able to use `onOpen` and `onClose` callbacks on `mz-sidenav-collapsible` on next release.
That should fix your ptoblem.
