### ISSUE TITLE
Bug in mz-icon-mdi

### ISSUE THREAD

**Issue by Rodrigo54** [sherweb/ng2-materialize#97]
I have a table component where I sort the data in a method similar to that.
```typescript
sortData() {
    ...
    if (this.reserve) {
        this.reserve = false;
        this.data.sort(naturalCompare);
        this.iconSort = 'chevron-down';
    } else {
        this.reserve = true;
        this.data.sort(naturalCompare).reverse();
        this.iconSort = 'chevron-up';
    }
    ...
}
```
This is the template for this component

```html
<table class="bordered">
    <thead>
      <tr>
        <th (click)="sortData()">Title
          <i *ngIf="iconSort" mz-icon-mdi [icon]="iconSort"></i>
        </th>
        ....
      </tr>
    </thead>
    <tbody>
    ....
    </tbody>
</table>
```
The behavior I observe is that the `mz-icon-mdi` directive adds the `.mdi-chevron-down` class but when the `iconSort` value changes it the directive add to the new icon class `.mdi-chevron-up` but the previous icon class dont removed from the element generating the bug which prevents the icon changes.
This bug does not occur with the `mz-icon` directive

Thank you for the excellent abstraction of the materialize css that you have been carrying out

ps: sorry for my bad english

**Comment by scote** [comment]
Thank you to report this bug. We will look at this one soon.

**Comment by scote** [comment]
As a workarround you could do this :
```
<i mz-icon-mdi *ngIf="reserve; else elseBlock;" [icon]="chevron-down"></i>
<ng-template #elseBlock>
    <i mz-icon-mdi [icon]="chevron-up"></i>
<ng-template>
```
