### ISSUE TITLE
Increase or decrease fontsize in the mz-navbar

### ISSUE THREAD

**Issue by agatsoh** [sherweb/ng2-materialize#98]
Not sure whether this is an issue or not but the font-size in the navbar comes out to be very small. If I use the heading like h1, h2 to increase or decrease the font the text location is not centered and goes above. 
How do we get the font size just like the ones you use in the navbar in the examples on the tutorial website.

**Comment by scote** [comment]
You can fork this repository to look at the navbar demo app page.
